# base
gamma: 0.95
action_space: 4



# learning strategy
online:
  use_online_learning: true
  start_epsilon: 1.0
  end_epsilon: 0.05
  epsilon_decay: 10000

# target network
target_network:
  use_target_network: true
  update_freq: 1000
