# input
input:
  input_height: 4
  input_width: 4

# embedding
embedding:
  embedding_dim: 16
  num_embeddings: 32

# residual block
residual_block:
  num_blocks: 2
  kernel_size: 3
  in_channels: 16
  out_channels: 16
  stride: 1
  padding: 1
  activation: "relu"

# output
output:
  output_dim: 4
